### PR TITLE
Fix compilation error

### LINKED ISSUE #2: action fails since 2/14
Hi,
I have been using this in my workflow for a few months now, since last saturday it fails. I see that there have been no changes in this repo for a few months, so it might even be some other problem; but I have no idea where else to even start, I know next to nothing about docker. It might have to do with go? It fails with this message:

2021-02-17T19:12:02.0646512Z Download action repository 'everphone-gmbh/cancel-previous-workflows@v5'
2021-02-17T19:12:04.4684278Z ##[group]Build container for action use: '/home/runner/work/_actions/everphone-gmbh/cancel-previous-workflows/v5/Dockerfile'.
2021-02-17T19:12:04.4752977Z ##[command]/usr/bin/docker build -t 5588e4:f070bb6ac2da4a12b2045069446dcc42 -f "/home/runner/work/_actions/everphone-gmbh/cancel-previous-workflows/v5/Dockerfile" "/home/runner/work/_actions/everphone-gmbh/cancel-previous-workflows/v5"
2021-02-17T19:12:06.1590041Z Sending build context to Docker daemon  8.192kB
2021-02-17T19:12:06.1591420Z 
2021-02-17T19:12:06.2186186Z Step 1/5 : FROM golang
2021-02-17T19:12:06.5229399Z latest: Pulling from library/golang
2021-02-17T19:12:06.6169245Z 0ecb575e629c: Pulling fs layer
2021-02-17T19:12:06.6174550Z 7467d1831b69: Pulling fs layer
2021-02-17T19:12:06.6175248Z feab2c490a3c: Pulling fs layer
2021-02-17T19:12:06.6175703Z f15a0f46f8c3: Pulling fs layer
2021-02-17T19:12:06.6176106Z 1517911a35d7: Pulling fs layer
2021-02-17T19:12:06.6176512Z 8e11185b0368: Pulling fs layer
2021-02-17T19:12:06.6177169Z f496c6a12b74: Pulling fs layer
2021-02-17T19:12:06.6178859Z 1517911a35d7: Waiting
2021-02-17T19:12:06.6179684Z 8e11185b0368: Waiting
2021-02-17T19:12:06.6180148Z f496c6a12b74: Waiting
2021-02-17T19:12:06.6180703Z f15a0f46f8c3: Waiting
2021-02-17T19:12:06.8058230Z 7467d1831b69: Verifying Checksum
2021-02-17T19:12:06.8059204Z 7467d1831b69: Download complete
2021-02-17T19:12:06.8458990Z feab2c490a3c: Verifying Checksum
2021-02-17T19:12:06.8459888Z feab2c490a3c: Download complete
2021-02-17T19:12:07.0149076Z 0ecb575e629c: Verifying Checksum
2021-02-17T19:12:07.0149641Z 0ecb575e629c: Download complete
2021-02-17T19:12:07.5535315Z 1517911a35d7: Verifying Checksum
2021-02-17T19:12:07.5536800Z 1517911a35d7: Download complete
2021-02-17T19:12:07.6550199Z f496c6a12b74: Verifying Checksum
2021-02-17T19:12:07.6551371Z f496c6a12b74: Download complete
2021-02-17T19:12:08.0765477Z f15a0f46f8c3: Verifying Checksum
2021-02-17T19:12:08.0766497Z f15a0f46f8c3: Download complete
2021-02-17T19:12:08.2088932Z 8e11185b0368: Verifying Checksum
2021-02-17T19:12:08.2090756Z 8e11185b0368: Download complete
2021-02-17T19:12:09.5159380Z 0ecb575e629c: Pull complete
2021-02-17T19:12:09.7901373Z 7467d1831b69: Pull complete
2021-02-17T19:12:10.0239333Z feab2c490a3c: Pull complete
2021-02-17T19:12:12.1124604Z f15a0f46f8c3: Pull complete
2021-02-17T19:12:20.0646009Z 1517911a35d7: Pull complete
2021-02-17T19:12:23.7690945Z 8e11185b0368: Pull complete
2021-02-17T19:12:24.0871585Z f496c6a12b74: Pull complete
2021-02-17T19:12:24.0920952Z Digest: sha256:f3f90f4d30866c1bdae90012b506bd5e557ce27ccd2510ed30a011c44c1affc8
2021-02-17T19:12:24.0933374Z Status: Downloaded newer image for golang:latest
2021-02-17T19:12:24.0946483Z  ---> 861b1afd1d13
2021-02-17T19:12:24.0946923Z Step 2/5 : WORKDIR /
2021-02-17T19:12:32.5719495Z  ---> Running in e7a8b69678b6
2021-02-17T19:12:33.4802855Z Removing intermediate container e7a8b69678b6
2021-02-17T19:12:33.4803563Z  ---> b2ce07334552
2021-02-17T19:12:33.4804303Z Step 3/5 : COPY runoverworkflows.go /runoverworkflows.go
2021-02-17T19:12:34.4367802Z  ---> 71888d1243d8
2021-02-17T19:12:34.4368470Z Step 4/5 : RUN go build -o /entrypoint
2021-02-17T19:12:34.4503294Z  ---> Running in 7bd4e1ba3d26
2021-02-17T19:12:35.2139573Z [91mgo: cannot find main module; see 'go help modules'
2021-02-17T19:12:35.3581205Z The command '/bin/sh -c go build -o /entrypoint' returned a non-zero code: 1
2021-02-17T19:12:35.3596028Z [0m
2021-02-17T19:12:35.3613778Z ##[warning]Docker build failed with exit code 1, back off 7.088 seconds before retry.

### PR DESCRIPTION
**Pull request by SiM07**
Close #2

### CODE REVIEW

**Comment by arthur5005** [comment]
Anything holding this up?

**Comment by forelabs** [comment]
@matansh can this be merged? :slightly_smiling_face: the action can not be used currently

**Review by matansh — APPROVED** [review]

**Comment by matansh** [comment]
sorry all, i need to setup notifications for this repo :)

thank you for contributing @SiM07 !!!

**Comment by SiM07** [comment]
As a workaround, and until @matansh releases a version `everphone-gmbh/cancel-previous-workflows@9e87f701234aafd39d0e9b1bd6de3c86953e1472`

**Comment by matansh** [comment]
@SiM07 version v5.1 released
Its late in my timezone but tomorrow i will set the repo up with a github action that releases new commits to master automatically (CD of sorts haha)

**Pull request merged**
